// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZoc49RFSY0rDXOZP0Kmp65PEevUbP6IU',
    appId: '1:269595857942:web:e5a9711caf2998a9dc9137',
    messagingSenderId: '269595857942',
    projectId: 'myapp-29f08',
    authDomain: 'myapp-29f08.firebaseapp.com',
    storageBucket: 'myapp-29f08.appspot.com',
    measurementId: 'G-7H45S1XPLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXiI-drfSkD9Xxmj0loL-P6EmZwn-MuE0',
    appId: '1:269595857942:android:77a31a030b8c5a00dc9137',
    messagingSenderId: '269595857942',
    projectId: 'myapp-29f08',
    storageBucket: 'myapp-29f08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa9agMKtNpeQF-mLuaxr_OSZQDCjOwSC0',
    appId: '1:269595857942:ios:f1f60235c864fdbddc9137',
    messagingSenderId: '269595857942',
    projectId: 'myapp-29f08',
    storageBucket: 'myapp-29f08.appspot.com',
    iosBundleId: 'com.damin.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa9agMKtNpeQF-mLuaxr_OSZQDCjOwSC0',
    appId: '1:269595857942:ios:e04509c497ec92c6dc9137',
    messagingSenderId: '269595857942',
    projectId: 'myapp-29f08',
    storageBucket: 'myapp-29f08.appspot.com',
    iosBundleId: 'com.damin.myapp.RunnerTests',
  );
}
